include:
  - path: ./modules/api/docker-compose.yml

services:
  frontend-angular:
    build:
      context: ./modules/spa
      dockerfile: Dockerfile.yml
    container_name: care_plus_spa
    ports:
      - "4200:4200"
    depends_on:
      api:
        condition: service_started
    restart: unless-stopped
